2017-07-15 10:04:24,378 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 10:04:24,554 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 10:05:33,554 - root - [ERROR]: False
None
2017-07-15 10:05:33,559 - root - [ERROR]: True
None
2017-07-15 10:05:33,562 - root - [ERROR]: JsonRpcError(-32603): 'class' -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    return operations.getNewsSummariesForUser(user_id, page_num)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 98, in getNewsSummariesForUser
    logging.error(news['class'] not in NEWS_CLASSES, exc_info = True)
KeyError: 'class'

2017-07-15 10:11:14,757 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 10:11:14,974 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 10:11:29,957 - root - [ERROR]: True
None
2017-07-15 10:11:29,960 - root - [ERROR]: True
None
2017-07-15 10:11:29,960 - root - [ERROR]: True
None
2017-07-15 10:11:29,961 - root - [ERROR]: True
None
2017-07-15 10:11:29,962 - root - [ERROR]: True
None
2017-07-15 10:11:29,962 - root - [ERROR]: True
None
2017-07-15 10:11:29,964 - root - [ERROR]: True
None
2017-07-15 10:11:29,964 - root - [ERROR]: True
None
2017-07-15 10:11:29,965 - root - [ERROR]: True
None
2017-07-15 10:11:29,965 - root - [ERROR]: True
None
2017-07-15 10:16:10,401 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 10:16:10,612 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 10:16:25,539 - root - [ERROR]: False
None
2017-07-15 10:16:25,548 - root - [ERROR]: True
None
2017-07-15 10:16:25,550 - root - [ERROR]: JsonRpcError(-32603): 'class' -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    return operations.getNewsSummariesForUser(user_id, page_num)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 98, in getNewsSummariesForUser
    logging.error(news['class'] not in NEWS_CLASSES, exc_info = True)
KeyError: 'class'

2017-07-15 10:25:12,248 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 10:25:12,433 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 10:25:30,620 - root - [ERROR]: News is invalid
None
2017-07-15 10:25:30,620 - root - [ERROR]: News is invalid
None
2017-07-15 10:25:30,622 - root - [ERROR]: News is invalid
None
2017-07-15 10:25:30,623 - root - [ERROR]: News is invalid
None
2017-07-15 10:25:30,624 - root - [ERROR]: News is invalid
None
2017-07-15 10:25:30,625 - root - [ERROR]: News is invalid
None
2017-07-15 10:25:30,625 - root - [ERROR]: News is invalid
None
2017-07-15 10:25:30,626 - root - [ERROR]: News is invalid
None
2017-07-15 10:25:30,629 - root - [ERROR]: News is invalid
None
2017-07-15 10:25:30,629 - root - [ERROR]: News is invalid
None
2017-07-15 10:30:14,246 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 10:30:14,439 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 10:30:35,284 - root - [ERROR]: True
None
2017-07-15 10:30:35,290 - root - [ERROR]: True
None
2017-07-15 10:30:35,295 - root - [ERROR]: True
None
2017-07-15 10:30:35,296 - root - [ERROR]: True
None
2017-07-15 10:30:35,297 - root - [ERROR]: True
None
2017-07-15 10:30:35,297 - root - [ERROR]: True
None
2017-07-15 10:30:35,300 - root - [ERROR]: True
None
2017-07-15 10:30:35,300 - root - [ERROR]: True
None
2017-07-15 10:30:35,301 - root - [ERROR]: True
None
2017-07-15 10:30:35,304 - root - [ERROR]: True
None
