2017-07-15 11:12:36,256 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 11:12:36,438 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 11:21:12,816 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 11:21:13,019 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 12:40:29,184 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 12:40:29,365 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 12:40:32,709 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-15 12:40:51,281 - root - [ERROR]: JsonRpcError(-32603): global name 'NEWS_CLASSES' is not defined -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    return operations.getNewsSummariesForUser(user_id, page_num)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 95, in getNewsSummariesForUser
    or news['class'] not in NEWS_CLASSES):
NameError: global name 'NEWS_CLASSES' is not defined

2017-07-15 13:02:20,030 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 13:02:20,208 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 13:02:23,619 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-15 13:07:57,876 - root - [ERROR]: JsonRpcError(-32603): global name 'NEWS_CLASSES' is not defined -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    return operations.getNewsSummariesForUser(user_id, page_num)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 95, in getNewsSummariesForUser
    or news['class'] not in NEWS_CLASSES):
NameError: global name 'NEWS_CLASSES' is not defined

2017-07-15 13:10:05,505 - root - [ERROR]: JsonRpcError(-32603): global name 'NEWS_CLASSES' is not defined -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    return operations.getNewsSummariesForUser(user_id, page_num)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 95, in getNewsSummariesForUser
    or news['class'] not in NEWS_CLASSES):
NameError: global name 'NEWS_CLASSES' is not defined

2017-07-15 13:14:56,433 - root - [ERROR]: JsonRpcError(-32603): global name 'NEWS_CLASSES' is not defined -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    return operations.getNewsSummariesForUser(user_id, page_num)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 95, in getNewsSummariesForUser
    or 'class' not in news
NameError: global name 'NEWS_CLASSES' is not defined

2017-07-15 13:16:23,004 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 13:16:23,184 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 13:16:26,925 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-15 13:16:33,551 - root - [ERROR]: False
None
2017-07-15 13:16:33,553 - root - [ERROR]: False
None
2017-07-15 13:16:33,554 - root - [ERROR]: True
None
2017-07-15 13:16:33,555 - root - [ERROR]: False
None
2017-07-15 13:16:33,556 - root - [ERROR]: False
None
2017-07-15 13:16:33,558 - root - [ERROR]: True
None
2017-07-15 13:16:33,559 - root - [ERROR]: False
None
2017-07-15 13:16:33,562 - root - [ERROR]: False
None
2017-07-15 13:16:33,563 - root - [ERROR]: True
None
2017-07-15 13:16:33,568 - root - [ERROR]: False
None
2017-07-15 13:16:33,568 - root - [ERROR]: False
None
2017-07-15 13:16:33,569 - root - [ERROR]: True
None
2017-07-15 13:17:18,066 - root - [ERROR]: False
None
2017-07-15 13:17:18,069 - root - [ERROR]: False
None
2017-07-15 13:17:18,075 - root - [ERROR]: True
None
2017-07-15 13:17:18,077 - root - [ERROR]: False
None
2017-07-15 13:17:18,077 - root - [ERROR]: False
None
2017-07-15 13:17:18,078 - root - [ERROR]: True
None
2017-07-15 13:17:18,079 - root - [ERROR]: False
None
2017-07-15 13:17:18,080 - root - [ERROR]: False
None
2017-07-15 13:17:18,081 - root - [ERROR]: True
None
2017-07-15 13:24:59,219 - root - [ERROR]: False
None
2017-07-15 13:24:59,223 - root - [ERROR]: False
None
2017-07-15 13:24:59,227 - root - [ERROR]: True
None
2017-07-15 13:24:59,229 - root - [ERROR]: False
None
2017-07-15 13:24:59,234 - root - [ERROR]: False
None
2017-07-15 13:24:59,243 - root - [ERROR]: True
None
2017-07-15 13:24:59,253 - root - [ERROR]: False
None
2017-07-15 13:24:59,254 - root - [ERROR]: False
None
2017-07-15 13:24:59,256 - root - [ERROR]: True
None
2017-07-15 13:24:59,259 - root - [ERROR]: False
None
2017-07-15 13:24:59,271 - root - [ERROR]: False
None
2017-07-15 13:24:59,274 - root - [ERROR]: True
None
2017-07-15 13:26:51,315 - root - [ERROR]: False
None
2017-07-15 13:26:51,317 - root - [ERROR]: False
None
2017-07-15 13:26:51,318 - root - [ERROR]: True
None
2017-07-15 13:26:51,319 - root - [ERROR]: False
None
2017-07-15 13:26:51,320 - root - [ERROR]: False
None
2017-07-15 13:26:51,322 - root - [ERROR]: True
None
2017-07-15 13:26:51,327 - root - [ERROR]: False
None
2017-07-15 13:26:51,332 - root - [ERROR]: False
None
2017-07-15 13:26:51,333 - root - [ERROR]: True
None
2017-07-15 13:26:51,340 - root - [ERROR]: False
None
2017-07-15 13:26:51,341 - root - [ERROR]: False
None
2017-07-15 13:26:51,342 - root - [ERROR]: True
None
2017-07-15 13:34:12,811 - root - [ERROR]: False
None
2017-07-15 13:34:12,813 - root - [ERROR]: False
None
2017-07-15 13:34:12,815 - root - [ERROR]: True
None
2017-07-15 13:34:12,816 - root - [ERROR]: False
None
2017-07-15 13:34:12,816 - root - [ERROR]: False
None
2017-07-15 13:34:12,817 - root - [ERROR]: True
None
2017-07-15 13:34:12,823 - root - [ERROR]: False
None
2017-07-15 13:34:12,828 - root - [ERROR]: False
None
2017-07-15 13:34:12,828 - root - [ERROR]: True
None
2017-07-15 13:34:12,829 - root - [ERROR]: False
None
2017-07-15 13:34:12,830 - root - [ERROR]: False
None
2017-07-15 13:34:12,831 - root - [ERROR]: True
None
2017-07-15 13:42:32,663 - root - [ERROR]: False
None
2017-07-15 13:42:32,665 - root - [ERROR]: False
None
2017-07-15 13:42:32,666 - root - [ERROR]: True
None
2017-07-15 13:42:32,667 - root - [ERROR]: False
None
2017-07-15 13:42:32,668 - root - [ERROR]: False
None
2017-07-15 13:42:32,669 - root - [ERROR]: True
None
2017-07-15 13:42:32,676 - root - [ERROR]: False
None
2017-07-15 13:42:32,679 - root - [ERROR]: False
None
2017-07-15 13:42:32,686 - root - [ERROR]: True
None
2017-07-15 13:42:32,696 - root - [ERROR]: False
None
2017-07-15 13:42:32,700 - root - [ERROR]: False
None
2017-07-15 13:42:32,701 - root - [ERROR]: True
None
2017-07-15 13:46:27,010 - root - [ERROR]: False
None
2017-07-15 13:46:27,013 - root - [ERROR]: False
None
2017-07-15 13:46:27,037 - root - [ERROR]: True
None
2017-07-15 13:46:27,040 - root - [ERROR]: False
None
2017-07-15 13:46:27,044 - root - [ERROR]: False
None
2017-07-15 13:46:27,045 - root - [ERROR]: True
None
2017-07-15 13:46:27,047 - root - [ERROR]: False
None
2017-07-15 13:46:27,049 - root - [ERROR]: False
None
2017-07-15 13:46:27,052 - root - [ERROR]: True
None
2017-07-15 13:46:27,053 - root - [ERROR]: False
None
2017-07-15 13:46:27,055 - root - [ERROR]: False
None
2017-07-15 13:46:27,056 - root - [ERROR]: True
None
2017-07-15 13:46:57,821 - root - [ERROR]: False
None
2017-07-15 13:46:57,829 - root - [ERROR]: False
None
2017-07-15 13:46:57,845 - root - [ERROR]: True
None
2017-07-15 13:46:57,848 - root - [ERROR]: False
None
2017-07-15 13:46:57,850 - root - [ERROR]: False
None
2017-07-15 13:46:57,850 - root - [ERROR]: True
None
2017-07-15 13:46:57,852 - root - [ERROR]: False
None
2017-07-15 13:46:57,853 - root - [ERROR]: False
None
2017-07-15 13:46:57,854 - root - [ERROR]: True
None
2017-07-15 13:46:57,856 - root - [ERROR]: False
None
2017-07-15 13:46:57,866 - root - [ERROR]: False
None
2017-07-15 13:46:57,872 - root - [ERROR]: True
None
2017-07-15 13:53:07,552 - root - [ERROR]: False
None
2017-07-15 13:53:07,554 - root - [ERROR]: False
None
2017-07-15 13:53:07,556 - root - [ERROR]: True
None
2017-07-15 13:53:07,560 - root - [ERROR]: False
None
2017-07-15 13:53:07,561 - root - [ERROR]: False
None
2017-07-15 13:53:07,562 - root - [ERROR]: True
None
2017-07-15 13:53:07,564 - root - [ERROR]: False
None
2017-07-15 13:53:07,567 - root - [ERROR]: False
None
2017-07-15 13:53:07,570 - root - [ERROR]: True
None
2017-07-15 13:53:07,582 - root - [ERROR]: False
None
2017-07-15 13:53:07,590 - root - [ERROR]: False
None
2017-07-15 13:53:07,592 - root - [ERROR]: True
None
2017-07-15 15:33:50,036 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 15:33:50,219 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 15:33:55,384 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-15 16:19:35,169 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 16:19:35,360 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 16:19:35,679 - root - [WARNING]: User does not have a preference model.
2017-07-15 16:21:41,637 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 16:21:41,816 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 16:22:29,606 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 16:22:29,796 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 16:27:58,565 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 16:27:58,741 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 16:30:50,352 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 16:30:50,542 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 16:32:53,699 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-15 16:32:53,881 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-15 16:32:54,207 - root - [WARNING]: User does not have a preference model.
2017-07-15 16:32:54,349 - root - [WARNING]: User does not have a preference model.
2017-07-15 16:32:54,444 - root - [WARNING]: User does not have a preference model.
2017-07-16 09:18:28,654 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-16 09:18:34,136 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 09:18:34,328 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 11:21:16,320 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 11:21:16,525 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 11:21:21,839 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-16 11:44:58,784 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 11:44:58,958 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 11:45:04,807 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-16 12:33:38,403 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 12:33:38,621 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 12:33:44,903 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-16 12:43:08,386 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 12:43:08,596 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 12:43:14,175 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-16 12:51:24,175 - pika.adapters.base_connection - [ERROR]: Fatal Socket Error: error(32, 'Broken pipe')
2017-07-16 12:51:24,179 - pika.adapters.base_connection - [WARNING]: Socket closed when connection was open
2017-07-16 12:51:24,179 - pika.connection - [WARNING]: Disconnected from RabbitMQ at donkey.rmq.cloudamqp.com:5672 (0): Not specified
2017-07-16 12:51:24,183 - root - [ERROR]: JsonRpcError(-32603): Internal JSON-RPC error. -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 34, in logNewsClickForUser
    return operations.logNewsClickForUser(user_id, news_id)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 126, in logNewsClickForUser
    cloudAMQP_client.sendMessage(message)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/../common/cloudAMQP_client.py", line 16, in sendMessage
    self.channel.basic_publish(exchange='', routing_key=self.queue_name, body=json.dumps(message))
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1978, in basic_publish
    mandatory, immediate)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 2065, in publish
    self._flush_output()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1174, in _flush_output
    *waiters)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
    raise exceptions.ConnectionClosed()
ConnectionClosed

2017-07-16 12:52:37,773 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 12:52:37,957 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 12:53:26,838 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 12:53:27,018 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 12:55:07,472 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 12:55:07,657 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 12:55:09,110 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-16 12:55:26,739 - root - [ERROR]: JsonRpcError(-32603): Cannot encode object: <pymongo.cursor.Cursor object at 0x7f5bd2b46b90> -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 29, in getNewsHistoryForUser
    return operations.getNewsHistoryForUser(user_id)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 118, in getNewsHistoryForUser
    return json.loads(dumps(history_news))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 274, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in _json_convert
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in <genexpr>
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/server.py", line 124, in send_message_with_response
    set_slave_okay, sock_info.is_mongos, use_find_cmd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 291, in get_message
    spec, self.fields, self.codec_options)
InvalidDocument: Cannot encode object: <pymongo.cursor.Cursor object at 0x7f5bd2b46b90>

2017-07-16 12:59:26,967 - root - [ERROR]: JsonRpcError(-32603): Cannot encode object: <pymongo.cursor.Cursor object at 0x7f5bd1c41ed0> -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 29, in getNewsHistoryForUser
    def getNewsHistoryForUser(self, user_id):
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 118, in getNewsHistoryForUser
    return json.loads(dumps(history_news))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 274, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in _json_convert
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in <genexpr>
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/server.py", line 124, in send_message_with_response
    set_slave_okay, sock_info.is_mongos, use_find_cmd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 291, in get_message
    spec, self.fields, self.codec_options)
InvalidDocument: Cannot encode object: <pymongo.cursor.Cursor object at 0x7f5bd1c41ed0>

2017-07-16 13:01:02,485 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 13:01:02,713 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 13:01:14,084 - root - [ERROR]: JsonRpcError(-32603): Cannot encode object: <pymongo.cursor.Cursor object at 0x7ff5a4ca5450> -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 31, in getNewsHistoryForUser
    return operations.getNewsHistoryForUser(user_id)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 118, in getNewsHistoryForUser
    return json.loads(dumps(history_news))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 274, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in _json_convert
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in <genexpr>
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/server.py", line 124, in send_message_with_response
    set_slave_okay, sock_info.is_mongos, use_find_cmd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 291, in get_message
    spec, self.fields, self.codec_options)
InvalidDocument: Cannot encode object: <pymongo.cursor.Cursor object at 0x7ff5a4ca5450>

2017-07-16 13:08:21,276 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 13:08:21,454 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 13:12:31,418 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 13:12:31,595 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 13:13:21,243 - root - [ERROR]: JsonRpcError(-32602): Invalid method parameter(s). -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
TypeError: add() takes exactly 3 arguments (1 given)

2017-07-16 13:15:22,756 - root - [ERROR]: JsonRpcError(-32602): Invalid method parameter(s). -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
TypeError: add() takes exactly 3 arguments (1 given)

2017-07-16 13:17:39,577 - root - [WARNING]: User does not have a preference model.
2017-07-16 13:19:36,266 - root - [ERROR]: JsonRpcError(-32603): Cannot encode object: <pymongo.cursor.Cursor object at 0x7f1250899610> -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 31, in getNewsHistoryForUser
    return operations.getNewsHistoryForUser(user_id)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 118, in getNewsHistoryForUser
    return json.loads(dumps(history_news))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 274, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in _json_convert
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in <genexpr>
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/server.py", line 124, in send_message_with_response
    set_slave_okay, sock_info.is_mongos, use_find_cmd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 291, in get_message
    spec, self.fields, self.codec_options)
InvalidDocument: Cannot encode object: <pymongo.cursor.Cursor object at 0x7f1250899610>

2017-07-16 13:24:44,370 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 13:24:44,549 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 13:31:12,063 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 13:31:12,253 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 13:39:22,818 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 13:39:22,991 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 13:40:22,818 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 13:40:22,986 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 13:41:40,028 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 13:41:40,204 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 13:53:04,578 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 13:53:04,809 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 13:53:14,677 - root - [ERROR]: JsonRpcError(-32603): global name 'itemgetter' is not defined -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 36, in getNewsHistoryForUser
    return operations.getNewsHistoryForUser(user_id)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 113, in getNewsHistoryForUser
    click_log = map(itemgetter('newsId'),list(db[CLICK_LOG_TABLE_NAME].find({'userId': user_id}, {'newsId':1})))
NameError: global name 'itemgetter' is not defined

2017-07-16 13:53:52,777 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 13:53:52,963 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 14:08:51,793 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 14:08:51,976 - pika.adapters.blocking_connection - [INFO]: Created channel=1
2017-07-16 14:08:59,518 - root - [INFO]: Starting HTTP server on localhost:5050
2017-07-16 14:34:30,393 - pika.adapters.base_connection - [INFO]: Connecting to 54.193.63.247:5672
2017-07-16 14:34:30,579 - pika.adapters.blocking_connection - [INFO]: Created channel=1
